language: node_js
sudo: false

node_js:
  - stable
cache:
  directories:
  - node_modules

branches:
  only:
    - master
install:
  - npm i -g codecov
script:
  - npm install
  - npm test
  - codecov
